.TH AutoFirma "1" "November 19, 2016"
.SH NAME
autofirma \- Herramienta para realizar y verificar firmas electronicas.

.SH SYNOPSIS
.B autofirma

.SH DESCRIPTION
\fBautofirma\fP  Herramienta para realizar y verifivar firmas electronicas.
AutoFirma es usada por las Administraciones Públicas españolas para poder
realizar trámites electrónicos.

.SH AUTHOR
This manual page was written by Alberto Fernandez <infjaf@gmail.com>.
