Document: autofirma
Title: Debian autofirma Manual
Author: <insert document author here>
Abstract: This manual describes what autofirma is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/autofirma/autofirma.sgml.gz

Format: postscript
Files: /usr/share/doc/autofirma/autofirma.ps.gz

Format: text
Files: /usr/share/doc/autofirma/autofirma.text.gz

Format: HTML
Index: /usr/share/doc/autofirma/html/index.html
Files: /usr/share/doc/autofirma/html/*.html
