#!/bin/bash
JAVA=java


if [ -f /usr/lib/jvm/java-17-openjdk-amd64/bin/java ];
then
	JAVA=/usr/lib/jvm/java-17-openjdk-amd64/bin/java
fi

if [ -f /usr/lib/jvm/java-8-openjdk-amd64/bin/java ];
then
	JAVA=/usr/lib/jvm/java-8-openjdk-amd64/bin/java
fi


if [ -f /usr/lib/jvm/java-11-openjdk-amd64/bin/java ];
then
	JAVA=/usr/lib/jvm/java-11-openjdk-amd64/bin/java
fi

if [-f /usr/lib/jvm/java-21-openjdk-amd64/bin/java ];
then
	JAVA=/usr/lib/jvm/java-21-openjdk-amd64/bin/java
fi




$JAVA -Djava.net.preferIPv4Stack=true -Djdk.tls.maxHandshakeMessageSize=524288 -jar /usr/share/autofirma/AutoFirma.jar "$@"
