#!/bin/sh -e

echo "Estamos en config 1"
# Source debconf library.
. /usr/share/debconf/confmodule
echo "Estamos en config 2"
db_input high autofirma/aviso_navegadores || true
echo "Estamos en config 3"
db_go
db_clear
